### PR TITLE
implement functionality for light bar LEDs

### PR DESCRIPTION
**Pull request by supervaka**
architecture is a WIP

### CODE REVIEW

**Comment by HWXLR8** [comment]
Is this ready for merge?

**Comment by supervaka** [comment]
> Is this ready for merge?

No, this was implemented by copy-pasting the `light_ws2812` library as `light_bar_ws2812.c` and `ring_light_ws2812.c`.

The copy-pasting was supposed to be temporary to test that it works at all. 

All things considered, I will probably redo this from current master.

**Comment by HWXLR8** [comment]
sounds good. I think resolving the TT issue is still top priority, and once it is resolved, the FW may look very different. Let's wait for now.

**Comment by HWXLR8** [comment]
closing this as stale

**Pull request closed without merging**
