### PR TITLE
Implement turntable HID lighting

### LINKED ISSUE #6: TT drops inputs on startup
@supervaka wondering if you have encountered such issues. Occurs on V1+V2. 

Steps to reproduce:

1. launch iidx
2. card in
3. select mode (in my case p-free)
4. when using the TT to select time, there are a few seconds of no response

Once the TT begins responding it is fine for the entire session and all sessions afterwards, but relaunching the game seems to cause it.

### PR DESCRIPTION
**Pull request by ASleepyCat**
Tested on a PWAN LMT. The HID descriptor changes were heavily based on [arcin-infinitas](https://github.com/kinetic-flow/arcin-infinitas).

* Switch from the `HID_DESCRIPTOR_JOYSTICK` template to manually writing the HID descriptors to have better control over it
  * Change turntable's logical range from `[-128, 127]` to `[0, 255]`
    * This fixes #6, based on the description and my testing. Interestingly, this range is also used in [roxy-firmware](https://github.com/veroxzik/roxy-firmware/blob/2be6eab0f6276b60e7f736b3e32bbb3db910a8d5/roxy/report_desc.h#L14C1-L15C23) which probably explains why the same behaviour shows with my AC knobs
  * In the future we'd probably want to remove the Z axis since that doesn't really make sense to have
* Add HID descriptors for the turntable lighting
* Remove unused code related to HID lighting
* Change turntable lighting code to light all LEDs instead of just two
* Remove extra `USB_Init()` call after `hwinit()`

If you want, I can remove the five extra HID button lights since they won't correspond to anything.

### CODE REVIEW

**Comment by HWXLR8** [comment]
@supervaka pls review

**Comment by HWXLR8** [comment]
TT HID tested and working. My only concern is that since our current implementation of lighting either has lighting controlled by HID reports, or controlled "reactively" depending on this flag:

```c
// flag to represent whether the LEDs are controlled by host or not
// when not controlled by host, LEDs light up while the corresponding
// button is held
bool reactive_led = true;
```
Then we cannot have any TT lighting effects which are not issued by the game, which to my knowledge is limited to just static colors (correct me if I am wrong). My solution to this would be a button combo which cycles through various TT effects, one of which is "HID TT". @supervaka @ASleepyCat  thoughts?

I also encounter a strange bug that I am unable to reproduce. I was testing each HID light one by one when I noticed the TT was emitting a very low intensity blue glow. Willing to ignore for now, but I will create an issue once this is merged.

**Comment by ASleepyCat** [comment]
A TT lighting mode switcher would be good, it would also allow the user to switch between spinning and scratch lighting modes too.

**Comment by HWXLR8** [comment]
I am fine with the current behaviour, we can implement the cycling effects in a separate commit (created issue https://github.com/HWXLR8/beef-board/issues/24 to track) will merge once @supervaka gives the OK

**Comment by supervaka** [comment]
Tested what is testable on my Dao PEE and behavior is intact.

> * Change turntable lighting code to light all LEDs instead of just two

Thank you for catching this. IIRC it was like that to check whether the LEDs work at all before working on fancier effects.

**Pull request merged**
